CREATE TABLE USERS (
    UID SERIAL PRIMARY KEY,
    UNAME TEXT UNIQUE NOT NULL,
    UEMAIL TEXT UNIQUE NOT NULL
);

CREATE TABLE AUTH (
    ID SERIAL PRIMARY KEY,
    UID INTEGER REFERENCES USERS(UID) ON DELETE CASCADE,
    HASH VARCHAR(255) NOT NULL,
    SALT VARCHAR(255) NOT NULL
);

CREATE TABLE OTP (
    ID SERIAL PRIMARY KEY,
    UID INTEGER REFERENCES USERS(UID) ON DELETE CASCADE,
    OTP VARCHAR(6),
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXPIRY_DATE TIMESTAMP NOT NULL
);

CREATE TABLE TOKEN(
    ID SERIAL PRIMARY KEY,
    UID INTEGER REFERENCES USERS(UID) ON DELETE CASCADE,
    TOKEN VARCHAR(255) NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE MEDIA (
    ID SERIAL PRIMARY KEY,
    UID INTEGER REFERENCES USERS(UID) ON DELETE CASCADE,
    MID INTEGER NOT NULL,
    MEDIA_NAME TEXT NOT NULL,
    MEDIA_URL TEXT NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AI_MODELS {
    ID SERIAL PRIMARY KEY,
    UID INTEGER REFERENCES USERS(UID) ON DELETE CASCADE,
    MNAME TEXT NOT NULL,
    MDESCRIPTION TEXT NOT NULL,
    MVERSION TEXT NOT NULL,
    MSUMMARY TEXT NOT NULL,
    MSTATUS TEXT NOT NULL,
    MPROFILEIMG TEXT NOT NULL,
    MIMG TEXT NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
};