CREATE TABLE users (
    uid SERIAL PRIMARY KEY,
    uname TEXT UNIQUE NOT NULL,
    uemail TEXT UNIQUE NOT NULL
);

CREATE TABLE auth (
    id SERIAL PRIMARY KEY,
    uid INTEGER REFERENCES users(uid) ON DELETE CASCADE,
    hash VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL
);

CREATE TABLE otp (
    id SERIAL PRIMARY KEY,
    uid INTEGER REFERENCES users(uid) ON DELETE CASCADE,
    otp VARCHAR(6),
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expiry_date TIMESTAMP NOT NULL
);
