# Generated by Django 5.0.6 on 2024-06-02 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0007_alter_video_video_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("mid", models.TextField(unique=True)),
                ("media_name", models.TextField()),
                ("media_url", models.FileField(upload_to="media/")),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="testApp.user",
                    ),
                ),
            ],
            options={
                "db_table": "media",
            },
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
