name: Lint Code Base

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  run-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"

      - name: Install dependencies
        run: |
          pip install flake8
          pip install -r requirements.txt

      - name: Lint Code Base
        run: |
          flake8 .
