name: Automated Testing

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"

      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r requirements.txt

      - name: Run Unit Tests
        working-directory: ./Broker/API
        run: |
          pytest test.py

  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"

      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r requirements.txt

      - name: Run Integration Tests
        working-directory: ./Agent/API
        run: |
          pytest test_cerberus.py
